### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by harshkumar1403** [Ashutosh-kv/JARVIS#4]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\other\assistant.py", line 12, in <module>
    engine = pyttsx3.init('sapi5')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'

**Comment by rishika1802** [comment]
same error

**Comment by mohammed-anas-khan** [comment]
Traceback (most recent call last):
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anas\Desktop\JARVIS-master\JARVIS-master\assistant.py", line 12, in <module>
    engine = pyttsx3.init('sapi5')
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'

**Comment by mohammed-anas-khan** [comment]
same error

**Comment by Majored** [comment]
Run ``pip install pyttsx3`` followed by ``pip install pypiwin32`` - https://pypi.org/project/pyttsx3/

**Comment by MrIceman** [comment]
FYI you should always ship a requirements.txt in your project so the people who check it out can simply do "pip install -r requirements.txt" to get all the dependencies.

To the author: do "pip freeze > requirements.txt" and push that txt file
